### ISSUE TITLE
Load pretrained EfficientNet models

### ISSUE THREAD

**Issue by cywinski** [nasa/pretrained-microscopy-models#12]
Hi!

Thanks for sharing your pretrained models!
Can you provide an example code for loading your pretrained EfficientNet models? Maybe I am missing something, but I think they cannot be loaded by `torch.hub.load` from `torchvision` repository.

Thanks in advance!

**Comment by JStuckner** [comment]
Sure! It’s super easy. Here is some example code.

https://github.com/nasa/pretrained-microscopy-models#how-load-pretrained-classification-model

There are also more detailed examples linked in the readme or in the examples folder.

**Comment by cywinski** [comment]
Thanks for the answer!

I saw the examples, and I was able to successfully load ResNet models, but I can't load EfficientNet models as they do not seem to be available through `torch.hub.load`.

When I run `torch.hub.list("pytorch/vision:v0.10.0")`:
```
['alexnet',
 'deeplabv3_mobilenet_v3_large',
 'deeplabv3_resnet101',
 'deeplabv3_resnet50',
 'densenet121',
 'densenet161',
 'densenet169',
 'densenet201',
 'fcn_resnet101',
 'fcn_resnet50',
 'googlenet',
 'inception_v3',
 'lraspp_mobilenet_v3_large',
 'mnasnet0_5',
 'mnasnet0_75',
 'mnasnet1_0',
 'mnasnet1_3',
 'mobilenet_v2',
 'mobilenet_v3_large',
 'mobilenet_v3_small',
 'resnet101',
 'resnet152',
 'resnet18',
 'resnet34',
 'resnet50',
 'resnext101_32x8d',
 'resnext50_32x4d',
 'shufflenet_v2_x0_5',
 'shufflenet_v2_x1_0',
 'squeezenet1_0',
 'squeezenet1_1',
 'vgg11',
 'vgg11_bn',
 'vgg13',
 'vgg13_bn',
 'vgg16',
 'vgg16_bn',
 'vgg19',
 'vgg19_bn',
 'wide_resnet101_2',
 'wide_resnet50_2']
```

**Comment by JStuckner** [comment]
Oh, I see. Sorry I misunderstood your question. I can’t quite remember where I got the efficientnet models. It wasn’t torch.hub. Maybe this? 

https://pytorch.org/vision/main/models/efficientnet.html

I leverage this library to load efficient net for segmentation models. https://github.com/qubvel/segmentation_models.pytorch. You might also get clues there? I’d try to dig deeper but I’m on mobile and traveling this week. Let me know if you aren’t able to find it.

**Comment by cywinski** [comment]
Loading from https://github.com/lukemelas/EfficientNet-PyTorch works. Thanks for a quick response!

**Comment by JStuckner** [comment]
That's great! I'm glad that ended up working. Let me know if you have any other issues. I'll be happy to help.
