### ISSUE TITLE
Shape Mismatch Error When Loading EfficientNetB4 Weights

### ISSUE THREAD

**Issue by ConMan05** [nasa/pretrained-microscopy-models#19]
I've downloaded the weights for EfficientNetB4, but I'm encountering a shape mismatch in some layers. Here’s the error message I received:

```
RuntimeError: Error(s) in loading state_dict for EfficientNetEncoder:
        size mismatch for _conv_stem.weight: copying a param with shape torch.Size([48, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([48, 1, 3, 3]).

```
I have `in_channels=1`. Are there any available weights compatible with this configuration?

**Comment by JStuckner** [comment]
No, there are no weight configurations for that.

You have two options:
1. Convert the input image to RGB. I always do that with my SEM and grayscale microscopy images and it works just fine.
2. Change the dimensions of the pretrained weights. I've never done this myself, but you could either drop two of the channels or average the channel weights. I'm not sure what is best. 

Overall my recommendation is to go with option 1. Let me know if there is some reason why you don't want to convert to RGB.
