### ISSUE TITLE
`get_segmentation_model()` nowhere to be found other than README instructions

### ISSUE THREAD

**Issue by sgbaird** [nasa/pretrained-microscopy-models#2]
https://github.com/nasa/pretrained-microscopy-models/search?q=get_segmentation_model

Since GitHub search is sometimes unreliable at finding every instance, took a look at a local fork in VS Code as well:

![image](https://user-images.githubusercontent.com/45469701/174214294-8d66cbb7-d0a0-450d-baa7-05d585164c9c.png)

**Comment by JStuckner** [comment]
Thanks for catching this! I've corrected the readme. 

It should be:
`model = pmm.segmentation_training.create_segmentation_model('Unet', 'resnet50', 'micronet', classes=3)`

The [multi-class segmentation example](https://github.com/nasa/pretrained-microscopy-models/blob/main/examples/multiclass_segmentation_example.ipynb) should work.

FYI, I also just updated the docstring for pmm.io.Dataset to make it more clear how to use.
