### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by whishei** [nasa/pretrained-microscopy-models#6]
I am trying to use your pretrained microscopy model for feature extraction, but I am running into some issues. Do you have any suggestions? 

I have tried using the pmm_model.predict(test_image); however the formatting of the test_image is incorrect for the model. I have the model working on my own training images already, but I am additionally trying to extract the features for use in another classifier. Any help would be appreciated!

**Comment by JStuckner** [comment]
What specific error are you getting? What is the format of the test_image? If you want to extract features you’ll need to first load the weights and then modify the model architecture to return the latent features. I plan to add an example of this within the next couple months
