### ISSUE TITLE
Bug in `image-micronet` weights download.

### ISSUE THREAD

**Issue by sebastian-sz** [nasa/pretrained-microscopy-models#7]
The issue is on this line of code:
https://github.com/nasa/pretrained-microscopy-models/blob/543e4b02be9f08922198bd7744409fa8b1e3749c/pretrained_microscopy_models/segmentation_training.py#L99

If we request `image-micronet` weights they are going to be ignored - this if statement returns false. If I instead request `imagemicronet` weights the code crashes as there is no such variant available.

Possible fix would be to modify the list:
`if encoder_weights in ['micronet', 'image-micronet']:`

**Comment by JStuckner** [comment]
Thanks for catching this! Fixed.
