### ISSUE TITLE
Issue on SE_ResNet-50 MicroNet Pre-trained model 

### ISSUE THREAD

**Issue by Kalrfou** [nasa/pretrained-microscopy-models#8]
Hello,

I am currently facing a problem when I try to use the SE_ResNet-50 MicroNet pre-trained model.  I encountered an HTTPS error during the process of downloading the model.

Thanks

**Comment by JStuckner** [comment]
Thanks for pointing this out! It looks like the links are indeed broken. I'm working with our cloud support team to get the links fixed and will let you know.

In the meantime, I hope some of the other encoders like SE_ResNeXt-50 will be useful. I understand if you are doing model selection you'll want to try both though, so I will try to get this fixed ASAP.

**Comment by Kalrfou** [comment]
The link still needs to be fixed. 
Thanks for your help.

**Comment by JStuckner** [comment]
I'm still waiting for IT. Will update.

**Comment by JStuckner** [comment]
The link is now working.
